# MPV Input Configuration 

# --- uosc Interface ---
mbtn_right    script-binding uosc/menu

# --- Navigation ---
SPACE {no-repeat} cycle pause; script-binding uosc/flash-pause-indicator
right         seek  5 exact; script-binding uosc/flash-timeline
left          seek -5 exact; script-binding uosc/flash-timeline
shift+right   seek  30 exact; script-binding uosc/flash-timeline
shift+left    seek -30 exact; script-binding uosc/flash-timeline

# --- Audio & Speed ---
WHEEL_UP      add volume  5; script-binding uosc/flash-volume
WHEEL_DOWN    add volume -5; script-binding uosc/flash-volume
up            add volume  5; script-binding uosc/flash-volume
down          add volume -5; script-binding uosc/flash-volume
m             no-osd cycle mute; script-binding uosc/flash-volume
[             add speed -0.25; script-binding uosc/flash-speed
]             add speed  0.25; script-binding uosc/flash-speed
\             set speed 1; script-binding uosc/flash-speed

# --- Context Menu ---
A             cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "no" #! Video > Cycle Aspect Ratio
s             script-binding uosc/subtitles          #! Subtitles > Select
S             script-binding uosc/load-subtitles     #! Subtitles > Load file
#             script-binding uosc/download-subtitles #! Subtitles > Download

a             script-binding uosc/audio              #! Audio > Select track
#             script-binding uosc/audio-device       #! Audio > Device

p             script-binding uosc/items              #! Playlist
c             script-binding uosc/chapters           #! Chapters

#             #! ---
o             script-binding uosc/open-file          #! Files > Open file
O             script-binding uosc/show-in-directory  #! Files > Show in folder
#             script-binding uosc/open-config-directory #! Files > Config directory

#             #! ---
ctrl+s        async screenshot                       #! Screenshot
alt+i         script-binding uosc/keybinds           #! Keybinds
#             script-binding uosc/update             #! Update uosc

q             quit                                   #! Quit
