# MPV Config
[extension.mp3]
save-position-on-quit=no
[extension.flac]
save-position-on-quit=no
[extension.wav]
save-position-on-quit=no
[extension.m4a]
save-position-on-quit=no
[extension.ogg]
save-position-on-quit=no
[extension.opus]
save-position-on-quit=no

[default]

input-ipc-server=/tmp/mpvsocket

# --- Video & Hardware ---
# Use OpenGL (Vulkan is unstable on Haswell/Hasvk)
gpu-api=opengl
# Hardware decoding via VA-API (Intel QuickSync)
hwdec=vaapi
vo=gpu
# EGL context is faster for X11/bspwm
gpu-context=x11egl
# High quality profile for 1080p
# profile=high-quality

# --- Playback Fluidity ---
#video-sync=display-resample
#interpolation=yes
#tscale=oversample

# --- UI (uosc integration) ---
# Disable default OSC and OSD bar
osc=no
osd-bar=no
# Borderless mode for tiling window managers
border=no

# --- Audio & Subtitles ---
# Priority for Russian and English tracks
alang=rus,eng
slang=rus,eng
# Do not enable subtitles by default
sid=no
# Force Pipewire output
ao=pipewire

# --- General Settings ---
save-position-on-quit=yes
cursor-autohide=1000

# --- Screenshots ---
screenshot-format=png
# Ensure this directory exists
screenshot-directory="~/Images/mpv_screenshots"
screenshot-template="%F-%p"
